workspace:
  path: /sb

kind: pipeline
type: docker
name: default
steps:
  - name: build
    image: node:12
    commands:
      - npm ci
      - npm run build

  - name: publish
    when: 
      branch:
        - master
    image: appleboy/drone-scp
    settings:
      host: web5svsvy.wh.hosting.zone
      port: 2244
      username:
        from_secret: dev_ssh_user
      key:
        from_secret: dev_ssh_key
      source: ./dist/*
      target: /home/web5svsvy/html/schlechtenburg.b12f.io/
      strip_components: 1
      rm: true
